name            'h0tbird-dhcp'
version         '0.0.1'
source          'https://github.com/h0tbird/puppet-dhcp'
author          'Marc Villacorta'
license         'GPL'
summary         'DHCP Module'
description     'Manages the DHCP service.'
project_page    'https://github.com/h0tbird/puppet-dhcp'
